"""add unique constraint to aqi readings

Revision ID: 63b738d15477
Revises: 7679efb5bbcb
Create Date: 2026-07-12 18:18:16.736905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b738d15477'
down_revision: Union[str, Sequence[str], None] = '7679efb5bbcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aqi_readings',
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aqi', sa.Float(), nullable=True),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('no2', sa.Float(), nullable=True),
    sa.Column('so2', sa.Float(), nullable=True),
    sa.Column('co', sa.Float(), nullable=True),
    sa.Column('o3', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['aqi_stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'timestamp', name='uq_station_timestamp')
    )
    op.create_index(op.f('ix_aqi_readings_station_id'), 'aqi_readings', ['station_id'], unique=False)
    op.create_index(op.f('ix_aqi_readings_timestamp'), 'aqi_readings', ['timestamp'], unique=False)
    op.alter_column('aqi_stations', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aqi_stations', 'state',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_aqi_readings_timestamp'), table_name='aqi_readings')
    op.drop_index(op.f('ix_aqi_readings_station_id'), table_name='aqi_readings')
    op.drop_table('aqi_readings')
    # ### end Alembic commands ###
