"""add weather columns

Revision ID: 69a2d58f7fe1
Revises: 63b738d15477
Create Date: 2026-07-13 17:37:08.924494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a2d58f7fe1'
down_revision: Union[str, Sequence[str], None] = '63b738d15477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aqi_readings', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('aqi_readings', sa.Column('humidity', sa.Float(), nullable=True))
    op.add_column('aqi_readings', sa.Column('wind_speed', sa.Float(), nullable=True))
    op.add_column('aqi_readings', sa.Column('wind_direction', sa.Float(), nullable=True))
    op.add_column('aqi_readings', sa.Column('pressure', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aqi_readings', 'pressure')
    op.drop_column('aqi_readings', 'wind_direction')
    op.drop_column('aqi_readings', 'wind_speed')
    op.drop_column('aqi_readings', 'humidity')
    op.drop_column('aqi_readings', 'temperature')
    # ### end Alembic commands ###
